graph TD
    A[开始] --> B[语句1]
    B --> C{判断1}
    C -- Y --> D[语句2]
    C -- N --> G
    D --> E{判断2}
    E -- Y --> F{判断3}
    E -- N --> H[语句3]

    // 修改：语句3直接指向语句5
    H --> K[语句5]
    // 修改：判断3如果是Y则返回到判断1
    F -- Y --> C
    // 修改：语句4直接指向语句5
    F -- N --> I[语句4]
    I --> K

    K --> L[语句6]
    L --> M[结束]
