graph TD
    S[开始] --> A[语句1]
    A --> B{判断1}
    B --N--> F[语句6] --> E[结束]
    B --Y--> C[语句2] --> D{判断2}
    D --N--> G[语句3] --> H[语句5] --> F
    D --Y--> I{判断3}
    I --N--> J[语句4] --> H
    I --Y--> B