graph LR
    Start[开始] --> A
    A --> |8| B
    A --> |16| C
    A --> |12| D
    B --> |17| E
    C --> |9| F
    D --> |8| F
    E --> |12| G
    F --> |15| G
    F --> |21| H
    F --> |18| I
    G --> |7| J
    H --> |8| J
    I --> |15| J
    J --> End[结束]
