server:
  port: 8082
spring:
  application:
    name: grpc-client

grpc:
  client:
    # gRPC配置的名字，GrpcClient注解会用到
    grpc-server:
      # gRPC服务端地址
      address: 'static://127.0.0.1:9252'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
