// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.demo.grpc.order;

public interface BuyerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Buyer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buyerId = 1;</code>
   * @return The buyerId.
   */
  int getBuyerId();
}
