// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.demo.grpc.order;

public final class OrderProto {
  private OrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Buyer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Buyer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddCartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\"\030\n\005Buyer\022\017\n\007buyerId\030\001 \001(\005\"" +
      "S\n\005Order\022\017\n\007orderId\030\001 \001(\005\022\021\n\tproductId\030\002" +
      " \001(\005\022\021\n\torderTime\030\003 \001(\003\022\023\n\013buyerRemark\030\004" +
      " \001(\t\"1\n\014ProductOrder\022\021\n\tproductId\030\001 \001(\005\022" +
      "\016\n\006number\030\002 \001(\005\"0\n\017AddCartResponse\022\014\n\004co" +
      "de\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"/\n\016DeductRespo" +
      "nse\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2.\n\nOr" +
      "derQuery\022 \n\nListOrders\022\006.Buyer\032\006.Order\"\000" +
      "0\0012?\n\013CartService\0220\n\tAddToCart\022\r.Product" +
      "Order\032\020.AddCartResponse\"\000(\0012C\n\014StockServ" +
      "ice\0223\n\013BatchDeduct\022\r.ProductOrder\032\017.Dedu" +
      "ctResponse\"\000(\0010\001B#\n\023com.demo.grpc.orderB" +
      "\nOrderProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Buyer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Buyer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Buyer_descriptor,
        new java.lang.String[] { "BuyerId", });
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "OrderId", "ProductId", "OrderTime", "BuyerRemark", });
    internal_static_ProductOrder_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductOrder_descriptor,
        new java.lang.String[] { "ProductId", "Number", });
    internal_static_AddCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AddCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddCartResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_DeductResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DeductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeductResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
