// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.demo.grpc.order;

public interface ProductOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 商品ID
   * </pre>
   *
   * <code>int32 productId = 1;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <pre>
   * 商品数量
   * </pre>
   *
   * <code>int32 number = 2;</code>
   * @return The number.
   */
  int getNumber();
}
